In [77]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
stepping	: 3
microcode	: 0xffffffff
cpu MHz		: 2000.216
cache size	: 39424 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data re

In [78]:
!cat /proc/meminfo

MemTotal:       13286944 kB
MemFree:         6070504 kB
MemAvailable:   10417252 kB
Buffers:          460328 kB
Cached:          3992488 kB
SwapCached:            0 kB
Active:           950944 kB
Inactive:        5805672 kB
Active(anon):       1480 kB
Inactive(anon):  2304484 kB
Active(file):     949464 kB
Inactive(file):  3501188 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               268 kB
Writeback:             0 kB
AnonPages:       2303696 kB
Mapped:           501436 kB
Shmem:              2156 kB
KReclaimable:     221740 kB
Slab:             278256 kB
SReclaimable:     221740 kB
SUnreclaim:        56516 kB
KernelStack:        5696 kB
PageTables:        10912 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6643472 kB
Committed_AS:    4483136 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       57848 kB
VmallocChunk:    

In [79]:
!!pip install pandas

['Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)',
 'Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)',
 'Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)',
 'Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)',
 'Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)',
 'Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)']

In [80]:
import pandas as pd


python basics 

Programming Languages used for Machine Learning:

Python
R

NumPy - Numerical Python

Advantages of Numpy Arrays:

Allows several Mathematical Operations
Faster operations

In [81]:
import numpy as np

List vs Numpy - Time Taken


In [82]:
from time import process_time

Time taken by a list

In [83]:
inbuilt_list=[ i for i in range(1,10000)]
start_time=process_time()
inbuilt_list=[ i +5  for i in range(1,10000)]
end_time=process_time()
print(end_time - start_time)


0.0006983789999992496


numpy array

In [84]:
np_array=np.array([i for i in range (1,1000)])

start_time = process_time()

np_array = np_array+ 5  

end_time = process_time()

print(end_time - start_time)

0.00012901799999909258


Numpy Arrays

In [85]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
     


[1 2 3 4 5]


numpy.ndarray

# creating a 1 dim array

In [86]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [87]:
a.shape

(5,)

In [88]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [89]:
b.shape

(2, 4)

In [90]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [91]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [92]:
# create a numpy array of ones

In [93]:
y=np.ones((6,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [94]:
# array of a particular value

In [95]:
z=np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [96]:
# create an identity matrix

In [97]:
a=np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [98]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.49714238 0.61559793 0.81068391 0.58867278]
 [0.12868502 0.32787286 0.74752467 0.6402137 ]
 [0.32123475 0.44503375 0.99910675 0.51063767]]


In [99]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[53 94 35 10 41]
 [74 65 14 72 78]
 [62 19 62 99 83]]


In [100]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [101]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [102]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array


In [103]:
c = np.random.randint(10,90,(5,5))
print(c)
# 10,90 denotes the bounds and (5,5) denotes size of arrya

[[63 72 81 30 44]
 [29 18 17 49 20]
 [26 22 44 13 36]
 [63 11 30 85 36]
 [85 35 28 35 15]]


In [104]:
# array dimension
print(c.shape)

(5, 5)


In [105]:
# number of dimensions
print(c.ndim)

2


In [106]:
# checking the data type of the values in the array
print(c.dtype)

int64


In [107]:
# number of elements in an array
print(c.size)
     

25


Mathematical operations on a np array

In [108]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [109]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
     

In [110]:
print (a)
print(b)

[[3 7 2]
 [7 4 2]
 [7 4 1]]
[[19 13 17]
 [12 11 11]
 [13 14 13]]


In [111]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
     

[[22 20 19]
 [19 15 13]
 [20 18 14]]
[[-16  -6 -15]
 [ -5  -7  -9]
 [ -6 -10 -12]]
[[57 91 34]
 [84 44 22]
 [91 56 13]]
[[0.15789474 0.53846154 0.11764706]
 [0.58333333 0.36363636 0.18181818]
 [0.53846154 0.28571429 0.07692308]]


In [112]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[22 20 19]
 [19 15 13]
 [20 18 14]]
[[-16  -6 -15]
 [ -5  -7  -9]
 [ -6 -10 -12]]
[[57 91 34]
 [84 44 22]
 [91 56 13]]
[[0.15789474 0.53846154 0.11764706]
 [0.58333333 0.36363636 0.18181818]
 [0.53846154 0.28571429 0.07692308]]


Array Manipulation

In [113]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[2 1 6]
 [9 3 6]]
(2, 3)


In [114]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[2 9]
 [1 3]
 [6 6]]
(3, 2)


In [115]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
     

[[3 0 9]
 [7 3 5]]
(2, 3)


In [116]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 7]
 [0 3]
 [9 5]]
(3, 2)


In [117]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[5 4 2]
 [1 3 8]]
(2, 3)


In [118]:

b = a.reshape(3,2)
print(b)
print(b.shape)

[[5 4]
 [2 1]
 [3 8]]
(3, 2)
