In [ ]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2200.214
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4400.42
clflush size	: 64
cache_alignment	: 64
address sizes

In [ ]:
!cat /proc/meminfo

MemTotal:       13286944 kB
MemFree:         9540848 kB
MemAvailable:   12372584 kB
Buffers:          119928 kB
Cached:          2911724 kB
SwapCached:            0 kB
Active:           430716 kB
Inactive:        3122648 kB
Active(anon):       1340 kB
Inactive(anon):   522452 kB
Active(file):     429376 kB
Inactive(file):  2600196 kB
Unevictable:           8 kB
Mlocked:               8 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:               888 kB
Writeback:             0 kB
AnonPages:        521756 kB
Mapped:           431164 kB
Shmem:              2072 kB
KReclaimable:      86432 kB
Slab:             123704 kB
SReclaimable:      86432 kB
SUnreclaim:        37272 kB
KernelStack:        5040 kB
PageTables:         7084 kB
SecPageTables:         0 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:     6643472 kB
Committed_AS:    2748972 kB
VmallocTotal:   34359738367 kB
VmallocUsed:       11532 kB
VmallocChunk:    

In [ ]:
!!pip install pandas

['Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)',
 'Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)',
 'Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)',
 'Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)',
 'Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)',
 'Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)']

In [ ]:
import pandas as pd


python basics 

Programming Languages used for Machine Learning:

Python
R

NumPy - Numerical Python

Advantages of Numpy Arrays:

Allows several Mathematical Operations
Faster operations

In [ ]:
import numpy as np

List vs Numpy - Time Taken


In [ ]:
from time import process_time

Time taken by a list

In [ ]:
inbuilt_list=[ i for i in range(1,10000)]
start_time=process_time()
inbuilt_list=[ i +5  for i in range(1,10000)]
end_time=process_time()
print(end_time - start_time)


0.0008742200000000366


numpy array

In [ ]:
np_array=np.array([i for i in range (1,1000)])

start_time = process_time()

np_array = np_array+ 5  

end_time = process_time()

print(end_time - start_time)

0.00015340399999974608


Numpy Arrays

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)
     


[1 2 3 4 5]


numpy.ndarray

# creating a 1 dim array

In [ ]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
a.shape

(5,)

In [ ]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
b.shape

(2, 4)

In [ ]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Initial Placeholders in numpy arrays

In [ ]:
# create a numpy array of Zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# create a numpy array of ones

In [ ]:
y=np.ones((6,7))
print(y)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# array of a particular value

In [ ]:
z=np.full((3,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [ ]:
# create an identity matrix

In [ ]:
a=np.eye(10)
print(a)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
# create a numpy array with random values
b = np.random.random((3,4))
print(b)

[[0.1058002  0.05256574 0.35222016 0.41839385]
 [0.28061813 0.11390989 0.54799543 0.51429546]
 [0.95808263 0.11967203 0.74228217 0.33805174]]


In [ ]:
# random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[18 72 14 62 22]
 [80 26 99 88 79]
 [54 14 96 68 26]]


In [ ]:
# array of evenly spaced values --> specifying the number of values required
d = np.linspace(10,30,5)
print(d)

[10. 15. 20. 25. 30.]


In [ ]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [ ]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[10 20 20 20 50]


numpy.ndarray

Analysing a numpy array


In [ ]:
c = np.random.randint(10,90,(5,5))
print(c)
# 10,90 denotes the bounds and (5,5) denotes size of arrya

[[83 55 27 83 80]
 [81 37 58 52 57]
 [47 49 29 39 76]
 [29 20 52 78 86]
 [41 81 30 11 30]]


In [ ]:
# array dimension
print(c.shape)

(5, 5)


In [ ]:
# number of dimensions
print(c.ndim)

2


In [ ]:
# checking the data type of the values in the array
print(c.dtype)

int64


In [ ]:
# number of elements in an array
print(c.size)
     

25


Mathematical operations on a np array

In [ ]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2)    # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [ ]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
     

In [ ]:
print (a)
print(b)

[[5 5 2]
 [8 5 8]
 [4 2 7]]
[[10 19 10]
 [18 16 16]
 [12 14 10]]


In [ ]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)
     

[[15 24 12]
 [26 21 24]
 [16 16 17]]
[[ -5 -14  -8]
 [-10 -11  -8]
 [ -8 -12  -3]]
[[ 50  95  20]
 [144  80 128]
 [ 48  28  70]]
[[0.5        0.26315789 0.2       ]
 [0.44444444 0.3125     0.5       ]
 [0.33333333 0.14285714 0.7       ]]


In [ ]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[15 24 12]
 [26 21 24]
 [16 16 17]]
[[ -5 -14  -8]
 [-10 -11  -8]
 [ -8 -12  -3]]
[[ 50  95  20]
 [144  80 128]
 [ 48  28  70]]
[[0.5        0.26315789 0.2       ]
 [0.44444444 0.3125     0.5       ]
 [0.33333333 0.14285714 0.7       ]]


Array Manipulation

In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[5 5 9]
 [4 4 9]]
(2, 3)


In [ ]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[5 4]
 [5 4]
 [9 9]]
(3, 2)


In [ ]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)
     

[[3 3 9]
 [8 9 7]]
(2, 3)


In [ ]:
trans2 = array.T
print(trans2)
print(trans2.shape)

[[3 8]
 [3 9]
 [9 7]]
(3, 2)


In [ ]:
# reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)


[[3 6 8]
 [7 4 4]]
(2, 3)


In [ ]:

b = a.reshape(3,2)
print(b)
print(b.shape)

[[3 6]
 [8 7]
 [4 4]]
(3, 2)


PANDAS


In [ ]:
import pandas as pd


In [ ]:
data=[1,2,3,0,44,123456,5,1234563,7,8,9,8]
series=pd.Series(data)
print (series)
print(type (series))

0           1
1           2
2           3
3           0
4          44
5      123456
6           5
7     1234563
8           7
9           8
10          9
11          8
dtype: int64
<class 'pandas.core.series.Series'>


In [ ]:
data=[1,2,3]
series=pd.Series(data,index=["a","b","c"])
print (series)
print(type (series))
print (series.loc["a"])
series.loc["b"]=100
print(series)

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>
1
a      1
b    100
c      3
dtype: int64


In [ ]:
data=[1,2,3,100,21,50]
series=pd.Series(data,index=["a","b","c","d","e","f"])
print(series[series>=50])

d    100
f     50
dtype: int64


In [ ]:
calories = {"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}

series = pd.Series(calories)
series.loc["Day 3"]+=500
print(series)

Day 1    1750
Day 2    2100
Day 3    2200
dtype: int64


In [ ]:
calories = {"Day 1": 1750, "Day 2": 2100, "Day 3": 1700}

series = pd.Series(calories)
print(series[series>=2000])

Day 2    2100
dtype: int64


#dataframes in pandas


In [ ]:

data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}
df = pd.DataFrame(data)
print(df)

        Name  Age
0  Spongebob   30
1    Patrick   35
2  Squidward   50


In [ ]:

data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}
df = pd.DataFrame(data,index=["e1","e2","e3",])
print(df)
print(df.loc["e1"])

         Name  Age
e1  Spongebob   30
e2    Patrick   35
e3  Squidward   50
Name    Spongebob
Age            30
Name: e1, dtype: object


In [ ]:
data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}
df = pd.DataFrame(data,index=["e1","e2","e3",])
print(df.iloc[0])

Name    Spongebob
Age            30
Name: e1, dtype: object


add a new column


In [ ]:
data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}
df = pd.DataFrame(data, index = ["e1", "e2", "e3",])
df["job"]=["a1","a2","a3"]

print(df)

         Name  Age job
e1  Spongebob   30  a1
e2    Patrick   35  a2
e3  Squidward   50  a3


add a new row

In [ ]:
data = {
    "Name": ["Spongebob", "Patrick", "Squidward"],
    "Age": [30, 35, 50]
}
df = pd.DataFrame(data, index = ["e1", "e2", "e3"])
new_row = pd.DataFrame([{ "Name": "alpha", "Age": 33 }],index=["e1"])
df=pd.concat([df,new_row])

print(df)

         Name  Age
e1  Spongebob   30
e2    Patrick   35
e3  Squidward   50
e1      alpha   33


importing in pandas csv and json files

In [ ]:
import pandas as pd
df = pd.read_csv('path')
df=pd.read_json('path')